# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tryOne.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtCore import * 
import sys


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                self.MainWindow = MainWindow
                MainWindow.resize(1247, 801)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.BackgroundImg = QtWidgets.QLabel(self.centralwidget)
                self.BackgroundImg.setGeometry(QtCore.QRect(0, 0, 1251, 801))
                self.BackgroundImg.setText("")
                self.BackgroundImg.setPixmap(QtGui.QPixmap("back.PNG"))
                self.BackgroundImg.setScaledContents(True)
                self.BackgroundImg.setWordWrap(False)
                self.BackgroundImg.setObjectName("BackgroundImg")
                self.BT12 = QtWidgets.QPushButton(self.centralwidget)
                self.BT12.setEnabled(True)
                self.BT12.setGeometry(QtCore.QRect(280, 260, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT12.setFont(font)
                self.BT12.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT12.setObjectName("BT12")
                self.MancalaLabel = QtWidgets.QLabel(self.centralwidget)
                self.MancalaLabel.setGeometry(QtCore.QRect(490, 20, 273, 51))
                font = QtGui.QFont()
                font.setFamily("Script MT Bold")
                font.setPointSize(25)
                font.setBold(True)
                font.setItalic(False)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                font.setKerning(False)
                self.MancalaLabel.setFont(font)
                self.MancalaLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.MancalaLabel.setStyleSheet("color: rgb(255, 252, 168);")
                self.MancalaLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.MancalaLabel.setFrameShadow(QtWidgets.QFrame.Plain)
                self.MancalaLabel.setScaledContents(False)
                self.MancalaLabel.setAlignment(QtCore.Qt.AlignCenter)
                self.MancalaLabel.setWordWrap(False)
                self.MancalaLabel.setObjectName("MancalaLabel")
                self.BoardImgLabel = QtWidgets.QLabel(self.centralwidget)
                self.BoardImgLabel.setGeometry(QtCore.QRect(70, 110, 1131, 591))
                self.BoardImgLabel.setText("")
                self.BoardImgLabel.setPixmap(QtGui.QPixmap("Board.PNG"))
                self.BoardImgLabel.setScaledContents(True)
                self.BoardImgLabel.setObjectName("BoardImgLabel")
                self.BT11 = QtWidgets.QPushButton(self.centralwidget)
                self.BT11.setEnabled(True)
                self.BT11.setGeometry(QtCore.QRect(410, 260, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT11.setFont(font)
                self.BT11.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT11.setObjectName("BT11")
                self.BT10 = QtWidgets.QPushButton(self.centralwidget)
                self.BT10.setEnabled(True)
                self.BT10.setGeometry(QtCore.QRect(540, 260, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT10.setFont(font)
                self.BT10.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT10.setObjectName("BT10")
                self.BT9 = QtWidgets.QPushButton(self.centralwidget)
                self.BT9.setEnabled(True)
                self.BT9.setGeometry(QtCore.QRect(670, 260, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT9.setFont(font)
                self.BT9.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT9.setObjectName("BT9")
                self.BT8 = QtWidgets.QPushButton(self.centralwidget)
                self.BT8.setEnabled(True)
                self.BT8.setGeometry(QtCore.QRect(800, 260, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT8.setFont(font)
                self.BT8.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT8.setObjectName("BT8")
                self.BT7 = QtWidgets.QPushButton(self.centralwidget)
                self.BT7.setEnabled(True)
                self.BT7.setGeometry(QtCore.QRect(930, 260, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT7.setFont(font)
                self.BT7.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT7.setObjectName("BT7")
                self.BT0 = QtWidgets.QPushButton(self.centralwidget)
                self.BT0.setEnabled(True)
                self.BT0.setGeometry(QtCore.QRect(280, 480, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT0.setFont(font)
                self.BT0.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT0.setObjectName("BT0")
                self.BT1 = QtWidgets.QPushButton(self.centralwidget)
                self.BT1.setEnabled(True)
                self.BT1.setGeometry(QtCore.QRect(410, 480, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT1.setFont(font)
                self.BT1.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT1.setObjectName("BT1")
                self.BT2 = QtWidgets.QPushButton(self.centralwidget)
                self.BT2.setEnabled(True)
                self.BT2.setGeometry(QtCore.QRect(540, 480, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT2.setFont(font)
                self.BT2.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT2.setObjectName("BT2")
                self.BT3 = QtWidgets.QPushButton(self.centralwidget)
                self.BT3.setEnabled(True)
                self.BT3.setGeometry(QtCore.QRect(670, 480, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT3.setFont(font)
                self.BT3.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT3.setObjectName("BT3")
                self.BT4 = QtWidgets.QPushButton(self.centralwidget)
                self.BT4.setEnabled(True)
                self.BT4.setGeometry(QtCore.QRect(800, 480, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT4.setFont(font)
                self.BT4.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT4.setObjectName("BT4")
                self.BT5 = QtWidgets.QPushButton(self.centralwidget)
                self.BT5.setEnabled(True)
                self.BT5.setGeometry(QtCore.QRect(930, 480, 61, 71))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                self.BT5.setFont(font)
                self.BT5.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent")
                self.BT5.setObjectName("BT5")
                self.BT13 = QtWidgets.QPushButton(self.centralwidget)
                self.BT13.setEnabled(True)
                self.BT13.setGeometry(QtCore.QRect(140, 280, 71, 121))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(35)
                self.BT13.setFont(font)
                self.BT13.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent;")
                self.BT13.setObjectName("BT13")
                self.BT6 = QtWidgets.QPushButton(self.centralwidget)
                self.BT6.setEnabled(True)
                self.BT6.setGeometry(QtCore.QRect(1060, 400, 71, 121))
                font = QtGui.QFont()
                font.setFamily("Simplified Arabic Fixed")
                font.setPointSize(35)
                self.BT6.setFont(font)
                self.BT6.setStyleSheet("color: rgb(255, 252, 168);background-color: transparent;")
                self.BT6.setObjectName("BT6")
                self.Player2Turn_2 = QtWidgets.QLabel(self.centralwidget)
                self.Player2Turn_2.setGeometry(QtCore.QRect(500, 170, 281, 31))
                font = QtGui.QFont()
                font.setPointSize(15)
                self.Player2Turn_2.setFont(font)
                self.Player2Turn_2.setStyleSheet("color :  rgb(255, 252, 168);")
                self.Player2Turn_2.setAlignment(QtCore.Qt.AlignCenter)
                self.Player2Turn_2.setObjectName("Player2Turn_2")
                self.Player1Turn = QtWidgets.QLabel(self.centralwidget)
                self.Player1Turn.setGeometry(QtCore.QRect(500, 610, 281, 31))
                font = QtGui.QFont()
                font.setPointSize(15)
                self.Player1Turn.setFont(font)
                self.Player1Turn.setStyleSheet("color :  rgb(255, 252, 168);")
                self.Player1Turn.setAlignment(QtCore.Qt.AlignCenter)
                self.Player1Turn.setObjectName("Player1Turn")
                self.SecCounterLabel = QtWidgets.QLabel(self.centralwidget)
                self.SecCounterLabel.setGeometry(QtCore.QRect(950, 160, 221, 71))
                font = QtGui.QFont()
                font.setPointSize(15)
                self.SecCounterLabel.setFont(font)
                self.SecCounterLabel.setStyleSheet("color :  rgb(255, 252, 168);")
                self.SecCounterLabel.setObjectName("SecCounterLabel")
                self.BackgroundImg.raise_()
                self.MancalaLabel.raise_()
                self.BoardImgLabel.raise_()
                self.BT12.raise_()
                self.BT11.raise_()
                self.BT10.raise_()
                self.BT9.raise_()
                self.BT8.raise_()
                self.BT7.raise_()
                self.BT0.raise_()
                self.BT1.raise_()
                self.BT2.raise_()
                self.BT3.raise_()
                self.BT4.raise_()
                self.BT5.raise_()
                self.BT13.raise_()
                self.BT6.raise_()
                self.Player2Turn_2.raise_()
                self.Player1Turn.raise_()
                self.SecCounterLabel.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                #! Make list of Buttons
                self.Btn_List = []
                self.Btn_List.append(self.BT0)
                self.Btn_List.append(self.BT1)
                self.Btn_List.append(self.BT2)
                self.Btn_List.append(self.BT3)
                self.Btn_List.append(self.BT4)
                self.Btn_List.append(self.BT5)
                self.Btn_List.append(self.BT6)
                self.Btn_List.append(self.BT7)
                self.Btn_List.append(self.BT8)
                self.Btn_List.append(self.BT9)
                self.Btn_List.append(self.BT10)
                self.Btn_List.append(self.BT11)
                self.Btn_List.append(self.BT12)
                self.Btn_List.append(self.BT13)

                #! Player 1 Starts
                self.player = 1
                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)
                self.Toggle_Player()

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.BT12.setText(_translate("MainWindow", "12"))
                self.MancalaLabel.setText(_translate("MainWindow", "Mancala Game "))
                self.BT11.setText(_translate("MainWindow", "11"))
                self.BT10.setText(_translate("MainWindow", "10"))
                self.BT9.setText(_translate("MainWindow", "9"))
                self.BT8.setText(_translate("MainWindow", "8"))
                self.BT7.setText(_translate("MainWindow", "7"))
                self.BT0.setText(_translate("MainWindow", "0"))
                self.BT1.setText(_translate("MainWindow", "1"))
                self.BT2.setText(_translate("MainWindow", "2"))
                self.BT3.setText(_translate("MainWindow", "3"))
                self.BT4.setText(_translate("MainWindow", "4"))
                self.BT5.setText(_translate("MainWindow", "5"))
                self.BT13.setText(_translate("MainWindow", "13"))
                self.BT6.setText(_translate("MainWindow", "6"))
                self.Player2Turn_2.setText(_translate("MainWindow", "Player 2 Turn"))
                self.Player1Turn.setText(_translate("MainWindow", "Player 1 Turn"))
                self.SecCounterLabel.setText(_translate("MainWindow", "1 Seconds Left !! "))
                
                
                self.BT0.clicked.connect(self.Pile_Pressed)
                self.BT1.clicked.connect(self.Pile_Pressed)
                self.BT2.clicked.connect(self.Pile_Pressed)
                self.BT3.clicked.connect(self.Pile_Pressed)
                self.BT4.clicked.connect(self.Pile_Pressed)
                self.BT5.clicked.connect(self.Pile_Pressed)
                self.BT6.clicked.connect(self.Pile_Pressed)
                self.BT7.clicked.connect(self.Pile_Pressed)
                self.BT8.clicked.connect(self.Pile_Pressed)
                self.BT9.clicked.connect(self.Pile_Pressed)
                self.BT10.clicked.connect(self.Pile_Pressed)
                self.BT11.clicked.connect(self.Pile_Pressed)
                self.BT12.clicked.connect(self.Pile_Pressed)
                self.BT13.clicked.connect(self.Pile_Pressed)
               
                #! Disable
                self.BT6.setEnabled(False)
                self.BT13.setEnabled(False)
                #! creating a timer object
                timer = QTimer(MainWindow)
                self.start = False
                #! 20 Second For time out 
                self.count = 0
                # adding action to timer
                timer.timeout.connect(self.showTime)
                # update the timer every second
                timer.start(100)
                
        def showTime(self):
                # checking if flag is true
                if self.start:
                        # incrementing the counter
                        self.count -= 1
        
                # timer is completed
                if self.count == 0:
                        # making flag false
                        self.start = False
                        # setting text to the label
                        self.SecCounterLabel.setText("Time Outtt!!!")
        
                if self.start:
                        # getting text from count
                        text = "Time Remaining:"+str(int(self.count/10 )) + " s"
                        # showing text
                        self.SecCounterLabel.setText(text)
        #! Function Called when a pile is clicked              
        def Pile_Pressed(self):
                sending_button = self.MainWindow.sender()
                #self.Player2Turn_2.setText('%s Clicked!' % str(sending_button.objectName()))
                self.Start_Game()
                self.Toggle_Player()
                
        def Start_Game(self):
                self.count = 20 * 10
                self.start = True

        def Toggle_Player(self):
                if self.player == 1:
                        self.player = 2
                        self.Player2Turn_2.setStyleSheet("background-color: transparent;")
                        self.Player1Turn.setStyleSheet("color :  rgb(255, 252, 168);")
                        for i in range(7):
                                self.Btn_List[i].setEnabled(True)
                                self.Btn_List[i].setStyleSheet("color :  rgb(255, 252, 168);background-color: transparent; ")
                        #! His Turn
                        for i in range(7,14):
                                self.Btn_List[i].setEnabled(False)
                                self.Btn_List[i].setStyleSheet("color :  rgb(219, 164, 13);background-color: transparent; ")
                # Player 2 Turn
                else: 
                        self.player = 1
                        self.Player2Turn_2.setStyleSheet(" color :  rgb(255, 252, 168)")
                        self.Player1Turn.setStyleSheet("background-color: transparent;")
                        for i in range(7):
                                self.Btn_List[i].setEnabled(False)
                                self.Btn_List[i].setStyleSheet("color :  rgb(219, 164, 13);background-color: transparent; ")
                        #! His Turn
                        for i in range(7,14):
                                self.Btn_List[i].setEnabled(True)
                                self.Btn_List[i].setStyleSheet("color :  rgb(255, 252, 168);background-color: transparent; ")
                        
                        
        
  




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
